services:
  wendy-apiserver:
    image: ylei2023/wendy-apiserver:latest
    ports:
      - "8001:8000"
    volumes:
      - ${PWD}/data:${PWD}/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GAME_ARCHIVE_PATH=${PWD}/data
      - DST_IMAGE=${DST_IMAGE:-swr.cn-north-4.myhuaweicloud.com/ylei/dontstarvetogether}
      - DATABASE_URL=sqlite:${PWD}/data/wendy.sqlite3
      - STEAM_API_KEY=${STEAM_API_KEY}
    restart: always
  wendy-plane:
    image: ylei2023/wendy-plane:latest
    ports:
      - "8000:80"
    restart: always
